parameters:
    sidus_eav_variant.family.class: Sidus\EAVVariantBundle\Model\VariantFamily
    sidus_eav_variant.validator.unique_variant.class: Sidus\EAVVariantBundle\Validator\Constraints\UniqueVariantValidator

services:
    sidus_eav_variant.validator.unique_variant:
        class: '%sidus_eav_variant.validator.unique_variant.class%'
        arguments: ['%sidus_eav_model.entity.data.class%']
        tags:
            - { name: validator.constraint_validator, alias: sidus_unique_variant }
