services:
    sidus_eav_variant.form.type.variant_collection:
        class: Sidus\EAVVariantBundle\Form\Type\VariantCollectionType
        arguments:
            - '@sidus_eav_model.family_configuration.handler'
            - '@sidus_eav_model.attribute_configuration.handler'
            - '%sidus_eav_variant.config.routes%'
        tags:
            - { name: form.type, alias: sidus_variant_collection }

    sidus_eav_variant.form.type.variant:
        class: Sidus\EAVVariantBundle\Form\Type\VariantType
        parent: sidus_eav_model.form.type.data
        tags:
            - { name: form.type, alias: sidus_variant }

    sidus_eav_variant.form.type.variant_family_selector:
        class: Sidus\EAVVariantBundle\Form\Type\VariantFamilySelectorType
        arguments: ['@sidus_eav_model.family_configuration.handler']
        tags:
            - { name: form.type, alias: sidus_variant_family_selector }

    sidus_eav_variant.form.type.axles:
        class: Sidus\EAVVariantBundle\Form\Type\AxlesType
        tags:
            - { name: form.type, alias: sidus_axles }
